[package]
name = "outparse"
version = "0.1.0"
authors = ["inakleinbottle <41870650+inakleinbottle@users.noreply.github.com>"]
edition = "2018"

[dependencies]
regex = "1.1.6"
lazy_static = "1.3.0"
serde = { version = "1.0.91", features = ["derive"] }
